##Renegotiation paper visualization
**3D visualization of consumer optimum**
This code will draw 3 countour surfaces representing the consumer's indifference surfaces.
The plot will be in a separate Mayavi visualizer window that can then be rotated and modified,
for example to add a cut plane.

In [1]:
%reload_ext watermark
%watermark -u -n -t 

Last updated: Mon Jun 29 2015 00:00:27 


In [2]:
import sys
sys.version

'2.7.10 |Anaconda 2.2.0 (64-bit)| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)]'

In [3]:
from __future__ import print_function
import numpy as np
import mayavi
import mayavi.mlab as mlab
from numpy import ogrid

In [4]:
import Contract

In [5]:
cM = Contract.Monopoly(beta = 0.75)
cM.y = [30, 60, 60]
cM.print_params()

beta    : 0.75
delta   : 1.0
guess   : [100 100 100]
kappa   : 0
r       : 0.0
rho     : 0.95
y       : [30, 60, 60]


In [26]:
cMF = cM.fcommit()         # the full commitment contract 
cMR = cM.reneg(cMF)        # what renegotiate to if full commitment unantipatedly undone     
print("yE: ",yE)
print("cMF:",cMF)
print("cMR:", cMR)

yE:  [30, 60, 60]
cMF: [ 54.65850338  40.377858    40.377858  ]
cMR: [ 54.65850338  45.94761399  33.94286558]


In [27]:
yE=cM.y
yE

[30, 60, 60]

In [28]:
c0, c1, c2 = ogrid[1:120, 1:120, 1:120]
rho = cM.rho
beta = cM.beta
def u(c):
    return ((1/(1-rho))*c**(1-rho))

#x, y, z, value = np.random.random((4, 3))*40
#value = np.ones(3)*23.0
#x = np.array([20,20,20 ])
#value = np.array([ 31,  31,  31.24444501])

In [29]:
x = np.array([yE[0], cMF[0], cMR[0]])
y = np.array([yE[1],  cMF[1],  cMR[1]])
z = np.array([yE[2],  cMF[2],  cMR[2]] ) 

#np.array([ 17.0,  17.0,  17.0]))
x,y,z

(array([ 30.        ,  54.65850338,  54.65850338]),
 array([ 60.        ,  40.377858  ,  45.94761399]),
 array([ 60.        ,  40.377858  ,  33.94286558]))

In [30]:
yE=cM.y
PUy = u(yE[0]) + beta*(u(yE[1]) + u(yE[2]))
yE, PUy

([30, 60, 60], 60.522856464796604)

In [31]:
PUMF = u(cMF[0]) + beta*(u(cMF[1]) + u(cMF[2]))
PUMF

60.522856464796604

In [37]:
ctr = mayavi.mlab.contour3d(u(c0) + beta*(u(c1) + u(c2)),
                            contours=[PUy],transparent=True)
mlab.outline()

mlab.points3d(x, y, z)

mlab.plot3d([yE[0], cMF[0]], [yE[1], cMF[1]], [yE[2], cMF[2]], tube_radius=.5)


mlab.show()

In [64]:
PUMF = u(cMR[0]) + beta*(u(cMR[1]) + u(cMR[2]))
PUMF

60.483863895558414

In [41]:
W =u(c0) + beta*(u(c1) + u(c2))

In [42]:
np.shape(W)

(199L, 199L, 199L)

In [43]:
W[100,100,100]

62.977595192233196